version: '3.7'

networks:
  cdc-using-debezium-network:
    name: cdc-using-debezium-network
    driver: bridge
    external: false

services:
  cdc-using-debezium-postgres:
    platform: linux/x86_64
    image: debezium/postgres:11
    container_name: cdc-using-debezium-postgres
    hostname: cdc-using-debezium-postgres
    restart: always
    ports:
      - '5443:5432'
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: postgres
      POSTGRES_DB: cdc-using-debezium
    volumes:
      - 'cdc-using-debezium-postgres-data:/var/lib/postgresql/data'
    networks:
      - cdc-using-debezium-network
  redis:
    image: redis
    ports:
      - 6379:6379
    depends_on:
      - cdc-using-debezium-postgres
    networks:
      - cdc-using-debezium-network
  debezium-server:
    platform: linux/x86_64
    image: debezium/server
    volumes:
      - ./conf:/debezium/conf
      - ./data:/debezium/data
    depends_on:
      - redis
    networks:
      - cdc-using-debezium-network

volumes:
  cdc-using-debezium-postgres-data:
    name: cdc-using-debezium-postgres-data
    driver: local
